// DO NOT MODIFY ! DO NOT MODIFY ! DO NOT MODIFY ! DO NOT MODIFY ! DO NOT MODIFY
// SteelScanner.cpp generated by reflex at Tue May  5 20:50:09 2009
// from steel.reflex using reflex.cpp.targetspec and reflex.cpp.implementation.codespec
// DO NOT MODIFY ! DO NOT MODIFY ! DO NOT MODIFY ! DO NOT MODIFY ! DO NOT MODIFY

#include "SteelScanner.h"


#line 20 "steel.reflex"

#include <iostream>
#include <sstream>
#include <cassert>
#include "SteelScanner.h"
#include "Ast.h"

#line 18 "SteelScanner.cpp"

SteelScanner::SteelScanner ()
    :
    ReflexCpp_::AutomatonApparatus(
        ms_state_table_,
        ms_state_count_,
        ms_transition_table_,
        ms_transition_count_,
        ms_accept_handler_count_,
        static_cast<ReflexCpp_::InputApparatus::IsInputAtEndMethod>(&SteelScanner::IsInputAtEnd_),
        static_cast<ReflexCpp_::InputApparatus::ReadNextAtomMethod>(&SteelScanner::ReadNextAtom_))
{


#line 95 "steel.reflex"

	m_char_cursor = 0;
	m_line = 1;
	m_script_name = "UNKNOWN SCRIPT";	
	m_pBuffer = "";
	m_token = NULL;

#line 41 "SteelScanner.cpp"

    ResetForNewInput();
}

SteelScanner::~SteelScanner ()
{
}

SteelScanner::Mode::Name SteelScanner::ScannerMode () const
{
    assert(InitialState_() != NULL);
    BarfCpp_::Size initial_node_index = InitialState_() - ms_state_table_;
    assert(initial_node_index < ms_state_count_);
    switch (initial_node_index)
    {
        default: assert(false && "invalid initial node index -- this should never happen"); return Mode::START_;
        case 0: return Mode::MAIN;
        case 111: return Mode::STRING_LITERAL_GUTS;
    }
}

void SteelScanner::ScannerMode (Mode::Name mode)
{
    assert(
        mode == Mode::MAIN ||
        mode == Mode::STRING_LITERAL_GUTS ||
        (false && "invalid Mode::Name"));
    InitialState_(ms_state_table_ + mode);
    assert(ScannerMode() == mode);
}

void SteelScanner::ResetForNewInput ()
{
    ReflexCpp_::AutomatonApparatus::ResetForNewInput_(ms_state_table_ + Mode::START_);


#line 103 "steel.reflex"

	m_line = 0;	

#line 82 "SteelScanner.cpp"
}

SteelParser::Token SteelScanner::Scan ()
{

#line 30 "steel.reflex"


#line 91 "SteelScanner.cpp"

    std::string accepted_string;
    // this is the main scanner loop.  it only breaks when an accept handler
    // returns or after the unmatched character handler, if certain conditions
    // exist (see comments below).
    while (true)
    {
        bool was_at_end_of_input_ = IsAtEndOfInput();

        BarfCpp_::Uint32 accept_handler_index_ = RunDfa_(accepted_string);
        // if no valid accept_handler_index_ was returned, then accepted_string
        // was filled with the first unaccepted input atom (i.e. the rejected
        // atom).  we'll call the HandleUnmatchedCharacter_ method on it.
        if (accept_handler_index_ >= ms_accept_handler_count_)
        {
            // if we were already at the end of input and no
            // rule was matched, break out of the loop.
            if (was_at_end_of_input_)
                break;

            assert(accepted_string.length() == 1);
            BarfCpp_::Uint8 rejected_atom = accepted_string[0];

            // execute the rejected-atom-handling actions.  the rejected atom
            // is in rejected_atom.  the loop is so a break statement inside
            // rejection_actions doesn't break out of the main scanner loop.
            do
            {

#line 107 "steel.reflex"

	//std::cerr << "Warning: unmatched input found:" 
	//<< '\'' << accepted_string << '\'' << std::endl;

#line 126 "SteelScanner.cpp"

            }
            while (false);
        }
        // otherwise, call the appropriate accept handler code.
        else
        {
            // execute the appropriate accept handler.
            // the accepted string is in accepted_string.
            switch (accept_handler_index_)
            {
                case 0:
                {

#line 141 "steel.reflex"

		return SteelParser::Token(SteelParser::Terminal::END_,NULL);
	
#line 145 "SteelScanner.cpp"

                }
                break;

                case 1:
                {

#line 146 "steel.reflex"

		m_line++;
	
#line 157 "SteelScanner.cpp"

                }
                break;

                case 2:
                {

#line 151 "steel.reflex"

		// Eat the comment
	
#line 169 "SteelScanner.cpp"

                }
                break;

                case 3:
                {

#line 156 "steel.reflex"

		// Eat it
	 
#line 181 "SteelScanner.cpp"

                }
                break;

                case 4:
                {

#line 161 "steel.reflex"

		m_token = new AstString(m_line,m_script_name);
		
		ScannerMode(Mode::STRING_LITERAL_GUTS);
	
#line 195 "SteelScanner.cpp"

                }
                break;

                case 5:
                {

#line 168 "steel.reflex"

		return SteelParser::Token(SteelParser::Terminal::BOOLEAN, new AstBoolean(m_line,m_script_name,true)) ;
	
#line 207 "SteelScanner.cpp"

                }
                break;

                case 6:
                {

#line 173 "steel.reflex"

		return SteelParser::Token(SteelParser::Terminal::BOOLEAN, new AstBoolean(m_line,m_script_name,false));
	
#line 219 "SteelScanner.cpp"

                }
                break;

                case 7:
                {

#line 178 "steel.reflex"

		return SteelParser::Token(SteelParser::Terminal::POP,NULL);
	
#line 231 "SteelScanner.cpp"

                }
                break;

                case 8:
                {

#line 183 "steel.reflex"

		return SteelParser::Token(SteelParser::Terminal::IMPORT,NULL);
	
#line 243 "SteelScanner.cpp"

                }
                break;

                case 9:
                {

#line 188 "steel.reflex"

		return SteelParser::Token(SteelParser::Terminal::SCOPE,NULL);
	
#line 255 "SteelScanner.cpp"

                }
                break;

                case 10:
                {

#line 193 "steel.reflex"

		return SteelParser::Token(SteelParser::Terminal::CAT,NULL);
	
#line 267 "SteelScanner.cpp"

                }
                break;

                case 11:
                {

#line 198 "steel.reflex"

		return SteelParser::Token(SteelParser::Terminal::DECREMENT,NULL);
	
#line 279 "SteelScanner.cpp"

                }
                break;

                case 12:
                {

#line 203 "steel.reflex"

		return SteelParser::Token(SteelParser::Terminal::INCREMENT,NULL);
	
#line 291 "SteelScanner.cpp"

                }
                break;

                case 13:
                {

#line 208 "steel.reflex"

		return SteelParser::Token(SteelParser::Terminal::INT,new AstInteger(m_line,m_script_name,ToInt(accepted_string)));
	
#line 303 "SteelScanner.cpp"

                }
                break;

                case 14:
                {

#line 213 "steel.reflex"

		return SteelParser::Token(SteelParser::Terminal::INT,new AstInteger(m_line,m_script_name,ToIntFromHex(accepted_string)));
	
#line 315 "SteelScanner.cpp"

                }
                break;

                case 15:
                {

#line 218 "steel.reflex"

		return SteelParser::Token(SteelParser::Terminal::FLOAT, new AstFloat(m_line,m_script_name,ToFloat(accepted_string)));
	
#line 327 "SteelScanner.cpp"

                }
                break;

                case 16:
                {

#line 223 "steel.reflex"

		return SteelParser::Token(SteelParser::Terminal::VAR_IDENTIFIER,new AstVarIdentifier(m_line,m_script_name,accepted_string));		
	
#line 339 "SteelScanner.cpp"

                }
                break;

                case 17:
                {

#line 228 "steel.reflex"

		return SteelParser::Token(SteelParser::Terminal::ARRAY_IDENTIFIER, new AstArrayIdentifier(m_line,m_script_name,accepted_string));
	
#line 351 "SteelScanner.cpp"

                }
                break;

                case 18:
                {

#line 233 "steel.reflex"

		return SteelParser::Token((SteelParser::Terminal::Name)accepted_string[0],NULL);
	
#line 363 "SteelScanner.cpp"

                }
                break;

                case 19:
                {

#line 238 "steel.reflex"

		return SteelParser::Token((SteelParser::Terminal::Name)accepted_string[0],NULL);
	
#line 375 "SteelScanner.cpp"

                }
                break;

                case 20:
                {

#line 243 "steel.reflex"

		 return SteelParser::Token(SteelParser::Terminal::LTE,NULL);
	
#line 387 "SteelScanner.cpp"

                }
                break;

                case 21:
                {

#line 248 "steel.reflex"

		 return SteelParser::Token(SteelParser::Terminal::GTE,NULL);
	
#line 399 "SteelScanner.cpp"

                }
                break;

                case 22:
                {

#line 253 "steel.reflex"

		return SteelParser::Token(SteelParser::Terminal::NE,NULL);
	
#line 411 "SteelScanner.cpp"

                }
                break;

                case 23:
                {

#line 258 "steel.reflex"

		 return SteelParser::Token(SteelParser::Terminal::EQ,NULL);
	 
#line 423 "SteelScanner.cpp"

                }
                break;

                case 24:
                {

#line 263 "steel.reflex"

		 return SteelParser::Token(SteelParser::Terminal::LT,NULL);
	
#line 435 "SteelScanner.cpp"

                }
                break;

                case 25:
                {

#line 268 "steel.reflex"

		 return SteelParser::Token(SteelParser::Terminal::GT,NULL);
	
#line 447 "SteelScanner.cpp"

                }
                break;

                case 26:
                {

#line 273 "steel.reflex"
 
		 return SteelParser::Token(SteelParser::Terminal::D,NULL);
	 
#line 459 "SteelScanner.cpp"

                }
                break;

                case 27:
                {

#line 278 "steel.reflex"
 
		 return SteelParser::Token(SteelParser::Terminal::AND,NULL);
	 
#line 471 "SteelScanner.cpp"

                }
                break;

                case 28:
                {

#line 283 "steel.reflex"
 
		 return SteelParser::Token(SteelParser::Terminal::OR,NULL);
	 
#line 483 "SteelScanner.cpp"

                }
                break;

                case 29:
                {

#line 288 "steel.reflex"

		 return SteelParser::Token(SteelParser::Terminal::NOT,NULL);
	
#line 495 "SteelScanner.cpp"

                }
                break;

                case 30:
                {

#line 293 "steel.reflex"

		 return SteelParser::Token(SteelParser::Terminal::WHILE,NULL);
	
#line 507 "SteelScanner.cpp"

                }
                break;

                case 31:
                {

#line 298 "steel.reflex"

		return SteelParser::Token(SteelParser::Terminal::DO,NULL);
	
#line 519 "SteelScanner.cpp"

                }
                break;

                case 32:
                {

#line 303 "steel.reflex"

		 return SteelParser::Token(SteelParser::Terminal::FOR,NULL);
	
#line 531 "SteelScanner.cpp"

                }
                break;

                case 33:
                {

#line 308 "steel.reflex"
 
		 return SteelParser::Token(SteelParser::Terminal::BREAK,NULL);
	
#line 543 "SteelScanner.cpp"

                }
                break;

                case 34:
                {

#line 313 "steel.reflex"
 
		 return SteelParser::Token(SteelParser::Terminal::CONTINUE,NULL);
	
#line 555 "SteelScanner.cpp"

                }
                break;

                case 35:
                {

#line 318 "steel.reflex"

		 return SteelParser::Token(SteelParser::Terminal::IF,NULL);
	
#line 567 "SteelScanner.cpp"

                }
                break;

                case 36:
                {

#line 323 "steel.reflex"

		 return SteelParser::Token(SteelParser::Terminal::ELSE,NULL);
	
#line 579 "SteelScanner.cpp"

                }
                break;

                case 37:
                {

#line 328 "steel.reflex"

		return SteelParser::Token(SteelParser::Terminal::RETURN,NULL);
	
#line 591 "SteelScanner.cpp"

                }
                break;

                case 38:
                {

#line 333 "steel.reflex"
 
		return SteelParser::Token(SteelParser::Terminal::FUNCTION,NULL);
	
#line 603 "SteelScanner.cpp"

                }
                break;

                case 39:
                {

#line 338 "steel.reflex"

		return SteelParser::Token(SteelParser::Terminal::FINAL,NULL);
	
#line 615 "SteelScanner.cpp"

                }
                break;

                case 40:
                {

#line 343 "steel.reflex"

		return SteelParser::Token(SteelParser::Terminal::VAR,NULL);
	
#line 627 "SteelScanner.cpp"

                }
                break;

                case 41:
                {

#line 348 "steel.reflex"

		return SteelParser::Token(SteelParser::Terminal::CONSTANT,NULL);
	
#line 639 "SteelScanner.cpp"

                }
                break;

                case 42:
                {

#line 353 "steel.reflex"

		return SteelParser::Token(SteelParser::Terminal::BAREWORD,new AstFuncIdentifier(m_line,m_script_name,accepted_string));
	
#line 651 "SteelScanner.cpp"

                }
                break;

                case 43:
                {

#line 363 "steel.reflex"

		// First, add the accepted_string to the string..
		AstString *pString = (AstString*)m_token;		
		pString->addChar(accepted_string[0]);
	
#line 665 "SteelScanner.cpp"

                }
                break;

                case 44:
                {

#line 370 "steel.reflex"

		AstString *pString = (AstString*)m_token;
		pString->addChar( AstString::getEscapedChar ( accepted_string[1] ) );
	
#line 678 "SteelScanner.cpp"

                }
                break;

                case 45:
                {

#line 378 "steel.reflex"
 
		AstString *pString = (AstString*)m_token;

		ScannerMode(Mode::MAIN);
		return SteelParser::Token(SteelParser::Terminal::STRING,m_token);
	
#line 693 "SteelScanner.cpp"

                }
                break;

                case 46:
                {

#line 386 "steel.reflex"

		// Error
	
#line 705 "SteelScanner.cpp"

                }
                break;

                default: assert(false && "this should never happen"); break;
            }
        }
    }


#line 33 "steel.reflex"

	

#line 720 "SteelScanner.cpp"
}

// ///////////////////////////////////////////////////////////////////////
// begin internal reflex-generated parser guts -- don't use
// ///////////////////////////////////////////////////////////////////////

bool SteelScanner::IsInputAtEnd_ ()
{

#line 125 "steel.reflex"


	return (m_pBuffer[m_char_cursor] == '\0');

#line 735 "SteelScanner.cpp"
}

BarfCpp_::Uint8 SteelScanner::ReadNextAtom_ ()
{

#line 116 "steel.reflex"


	if( m_pBuffer[m_char_cursor] == '\0')
		return '\n';
	else
		return m_pBuffer[m_char_cursor++];


#line 750 "SteelScanner.cpp"
}

// the order of the states indicates priority (only for accept states).
// the lower the state's index in this array, the higher its priority.
ReflexCpp_::AutomatonApparatus::DfaState_ const SteelScanner::ms_state_table_[] =
{
    { 47, 2, ms_transition_table_+0 },
    { 47, 46, ms_transition_table_+2 },
    { 3, 2, ms_transition_table_+48 },
    { 1, 0, ms_transition_table_+50 },
    { 29, 1, ms_transition_table_+50 },
    { 22, 0, ms_transition_table_+51 },
    { 4, 0, ms_transition_table_+51 },
    { 19, 3, ms_transition_table_+51 },
    { 16, 4, ms_transition_table_+54 },
    { 19, 0, ms_transition_table_+58 },
    { 19, 1, ms_transition_table_+58 },
    { 12, 0, ms_transition_table_+59 },
    { 19, 1, ms_transition_table_+59 },
    { 11, 0, ms_transition_table_+60 },
    { 19, 1, ms_transition_table_+60 },
    { 2, 2, ms_transition_table_+61 },
    { 13, 3, ms_transition_table_+63 },
    { 47, 1, ms_transition_table_+66 },
    { 15, 1, ms_transition_table_+67 },
    { 47, 2, ms_transition_table_+68 },
    { 47, 3, ms_transition_table_+70 },
    { 14, 3, ms_transition_table_+73 },
    { 13, 2, ms_transition_table_+76 },
    { 10, 1, ms_transition_table_+78 },
    { 9, 0, ms_transition_table_+79 },
    { 18, 0, ms_transition_table_+79 },
    { 24, 1, ms_transition_table_+79 },
    { 20, 0, ms_transition_table_+80 },
    { 19, 1, ms_transition_table_+80 },
    { 23, 0, ms_transition_table_+81 },
    { 25, 1, ms_transition_table_+81 },
    { 21, 0, ms_transition_table_+82 },
    { 19, 3, ms_transition_table_+82 },
    { 17, 4, ms_transition_table_+85 },
    { 42, 4, ms_transition_table_+89 },
    { 42, 6, ms_transition_table_+93 },
    { 42, 6, ms_transition_table_+99 },
    { 27, 4, ms_transition_table_+105 },
    { 42, 6, ms_transition_table_+109 },
    { 42, 6, ms_transition_table_+115 },
    { 42, 5, ms_transition_table_+121 },
    { 42, 6, ms_transition_table_+126 },
    { 33, 4, ms_transition_table_+132 },
    { 42, 6, ms_transition_table_+136 },
    { 42, 6, ms_transition_table_+142 },
    { 42, 7, ms_transition_table_+148 },
    { 42, 6, ms_transition_table_+155 },
    { 41, 4, ms_transition_table_+161 },
    { 42, 6, ms_transition_table_+165 },
    { 42, 6, ms_transition_table_+171 },
    { 42, 6, ms_transition_table_+177 },
    { 42, 6, ms_transition_table_+183 },
    { 34, 4, ms_transition_table_+189 },
    { 26, 6, ms_transition_table_+193 },
    { 31, 4, ms_transition_table_+199 },
    { 42, 6, ms_transition_table_+203 },
    { 42, 6, ms_transition_table_+209 },
    { 42, 6, ms_transition_table_+215 },
    { 36, 4, ms_transition_table_+221 },
    { 42, 11, ms_transition_table_+225 },
    { 42, 6, ms_transition_table_+236 },
    { 42, 6, ms_transition_table_+242 },
    { 42, 6, ms_transition_table_+248 },
    { 6, 4, ms_transition_table_+254 },
    { 42, 6, ms_transition_table_+258 },
    { 42, 5, ms_transition_table_+264 },
    { 42, 6, ms_transition_table_+269 },
    { 39, 4, ms_transition_table_+275 },
    { 42, 6, ms_transition_table_+279 },
    { 32, 4, ms_transition_table_+285 },
    { 42, 6, ms_transition_table_+289 },
    { 42, 6, ms_transition_table_+295 },
    { 42, 6, ms_transition_table_+301 },
    { 42, 6, ms_transition_table_+307 },
    { 42, 6, ms_transition_table_+313 },
    { 42, 6, ms_transition_table_+319 },
    { 38, 4, ms_transition_table_+325 },
    { 42, 6, ms_transition_table_+329 },
    { 35, 4, ms_transition_table_+335 },
    { 42, 6, ms_transition_table_+339 },
    { 42, 6, ms_transition_table_+345 },
    { 29, 4, ms_transition_table_+351 },
    { 42, 6, ms_transition_table_+355 },
    { 28, 4, ms_transition_table_+361 },
    { 42, 6, ms_transition_table_+365 },
    { 42, 6, ms_transition_table_+371 },
    { 7, 4, ms_transition_table_+377 },
    { 42, 6, ms_transition_table_+381 },
    { 42, 6, ms_transition_table_+387 },
    { 42, 6, ms_transition_table_+393 },
    { 42, 6, ms_transition_table_+399 },
    { 42, 6, ms_transition_table_+405 },
    { 37, 4, ms_transition_table_+411 },
    { 42, 6, ms_transition_table_+415 },
    { 42, 6, ms_transition_table_+421 },
    { 42, 6, ms_transition_table_+427 },
    { 5, 4, ms_transition_table_+433 },
    { 42, 6, ms_transition_table_+437 },
    { 42, 6, ms_transition_table_+443 },
    { 42, 6, ms_transition_table_+449 },
    { 42, 6, ms_transition_table_+455 },
    { 8, 4, ms_transition_table_+461 },
    { 42, 5, ms_transition_table_+465 },
    { 42, 6, ms_transition_table_+470 },
    { 40, 4, ms_transition_table_+476 },
    { 42, 6, ms_transition_table_+480 },
    { 42, 6, ms_transition_table_+486 },
    { 42, 6, ms_transition_table_+492 },
    { 42, 6, ms_transition_table_+498 },
    { 30, 4, ms_transition_table_+504 },
    { 0, 46, ms_transition_table_+508 },
    { 47, 2, ms_transition_table_+554 },
    { 47, 5, ms_transition_table_+556 },
    { 43, 0, ms_transition_table_+561 },
    { 45, 0, ms_transition_table_+561 },
    { 43, 2, ms_transition_table_+561 },
    { 44, 0, ms_transition_table_+563 },
    { 46, 5, ms_transition_table_+563 }
};
BarfCpp_::Size const SteelScanner::ms_state_count_ = sizeof(SteelScanner::ms_state_table_) / sizeof(*SteelScanner::ms_state_table_);

ReflexCpp_::AutomatonApparatus::DfaTransition_ const SteelScanner::ms_transition_table_[] =
{
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::CONDITIONAL, 2, 0, ms_state_table_+1 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::CONDITIONAL, 2, 2, ms_state_table_+110 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 9, 0, ms_state_table_+2 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 10, 0, ms_state_table_+3 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 32, 0, ms_state_table_+2 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 33, 0, ms_state_table_+4 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 34, 0, ms_state_table_+6 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 36, 0, ms_state_table_+7 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 37, 0, ms_state_table_+9 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 43, 0, ms_state_table_+10 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 44, 0, ms_state_table_+9 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 45, 0, ms_state_table_+12 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 47, 0, ms_state_table_+14 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 48, 0, ms_state_table_+16 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 58, 0, ms_state_table_+23 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 59, 0, ms_state_table_+25 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 60, 0, ms_state_table_+26 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 61, 0, ms_state_table_+28 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 62, 0, ms_state_table_+30 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 64, 0, ms_state_table_+32 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 91, 0, ms_state_table_+9 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 97, 0, ms_state_table_+35 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 98, 0, ms_state_table_+38 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 99, 0, ms_state_table_+43 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 100, 0, ms_state_table_+53 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 101, 0, ms_state_table_+55 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 102, 0, ms_state_table_+59 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 105, 0, ms_state_table_+77 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 110, 0, ms_state_table_+79 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 111, 0, ms_state_table_+82 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 112, 0, ms_state_table_+84 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 113, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 114, 0, ms_state_table_+87 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 115, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 116, 0, ms_state_table_+93 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 117, 0, ms_state_table_+97 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 118, 0, ms_state_table_+102 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 119, 0, ms_state_table_+105 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 123, 0, ms_state_table_+25 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 125, 0, ms_state_table_+25 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 40, 42, ms_state_table_+9 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 49, 57, ms_state_table_+22 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 93, 94, ms_state_table_+9 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 103, 104, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 106, 109, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 120, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 9, 0, ms_state_table_+2 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 32, 0, ms_state_table_+2 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 61, 0, ms_state_table_+5 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+8 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+8 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 122, ms_state_table_+8 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+8 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+8 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+8 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 122, ms_state_table_+8 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 43, 0, ms_state_table_+11 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 45, 0, ms_state_table_+13 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 47, 0, ms_state_table_+15 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 1, 9, ms_state_table_+15 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 11, 255, ms_state_table_+15 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 46, 0, ms_state_table_+17 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 120, 0, ms_state_table_+20 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+19 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+18 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+18 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 46, 0, ms_state_table_+17 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+19 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+21 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 70, ms_state_table_+21 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 102, ms_state_table_+21 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+21 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 70, ms_state_table_+21 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 102, ms_state_table_+21 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 46, 0, ms_state_table_+17 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+22 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 58, 0, ms_state_table_+24 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 61, 0, ms_state_table_+27 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 61, 0, ms_state_table_+29 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 61, 0, ms_state_table_+31 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+33 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+33 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 122, ms_state_table_+33 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+33 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+33 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+33 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 122, ms_state_table_+33 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 110, 0, ms_state_table_+36 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 109, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 111, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 100, 0, ms_state_table_+37 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 99, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 101, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 114, 0, ms_state_table_+39 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 113, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 115, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 101, 0, ms_state_table_+40 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 100, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 102, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 97, 0, ms_state_table_+41 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 98, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 107, 0, ms_state_table_+42 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 106, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 108, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 111, 0, ms_state_table_+44 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 110, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 112, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 110, 0, ms_state_table_+45 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 109, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 111, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 115, 0, ms_state_table_+46 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 116, 0, ms_state_table_+48 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 114, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 117, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 116, 0, ms_state_table_+47 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 115, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 117, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 105, 0, ms_state_table_+49 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 104, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 106, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 110, 0, ms_state_table_+50 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 109, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 111, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 117, 0, ms_state_table_+51 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 116, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 118, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 101, 0, ms_state_table_+52 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 100, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 102, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 111, 0, ms_state_table_+54 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 110, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 112, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 108, 0, ms_state_table_+56 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 107, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 109, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 115, 0, ms_state_table_+57 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 114, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 116, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 101, 0, ms_state_table_+58 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 100, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 102, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 97, 0, ms_state_table_+60 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 105, 0, ms_state_table_+64 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 111, 0, ms_state_table_+68 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 117, 0, ms_state_table_+70 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 98, 104, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 106, 110, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 112, 116, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 118, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 108, 0, ms_state_table_+61 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 107, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 109, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 115, 0, ms_state_table_+62 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 114, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 116, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 101, 0, ms_state_table_+63 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 100, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 102, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 110, 0, ms_state_table_+65 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 109, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 111, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 97, 0, ms_state_table_+66 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 98, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 108, 0, ms_state_table_+67 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 107, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 109, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 114, 0, ms_state_table_+69 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 113, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 115, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 110, 0, ms_state_table_+71 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 109, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 111, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 99, 0, ms_state_table_+72 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 98, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 100, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 116, 0, ms_state_table_+73 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 115, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 117, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 105, 0, ms_state_table_+74 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 104, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 106, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 111, 0, ms_state_table_+75 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 110, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 112, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 110, 0, ms_state_table_+76 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 109, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 111, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 102, 0, ms_state_table_+78 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 101, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 103, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 111, 0, ms_state_table_+80 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 110, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 112, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 116, 0, ms_state_table_+81 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 115, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 117, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 114, 0, ms_state_table_+83 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 113, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 115, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 111, 0, ms_state_table_+85 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 110, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 112, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 112, 0, ms_state_table_+86 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 111, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 113, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 101, 0, ms_state_table_+88 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 100, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 102, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 116, 0, ms_state_table_+89 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 115, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 117, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 117, 0, ms_state_table_+90 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 116, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 118, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 114, 0, ms_state_table_+91 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 113, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 115, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 110, 0, ms_state_table_+92 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 109, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 111, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 114, 0, ms_state_table_+94 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 113, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 115, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 117, 0, ms_state_table_+95 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 116, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 118, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 101, 0, ms_state_table_+96 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 100, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 102, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 115, 0, ms_state_table_+98 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 114, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 116, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 105, 0, ms_state_table_+99 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 104, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 106, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 110, 0, ms_state_table_+100 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 109, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 111, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 103, 0, ms_state_table_+101 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 102, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 104, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 97, 0, ms_state_table_+103 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 98, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 114, 0, ms_state_table_+104 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 113, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 115, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 104, 0, ms_state_table_+106 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 103, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 105, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 105, 0, ms_state_table_+107 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 104, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 106, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 108, 0, ms_state_table_+108 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 107, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 109, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 101, 0, ms_state_table_+109 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 100, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 102, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 48, 57, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 97, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 9, 0, ms_state_table_+2 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 10, 0, ms_state_table_+3 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 32, 0, ms_state_table_+2 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 33, 0, ms_state_table_+4 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 34, 0, ms_state_table_+6 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 36, 0, ms_state_table_+7 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 37, 0, ms_state_table_+9 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 43, 0, ms_state_table_+10 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 44, 0, ms_state_table_+9 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 45, 0, ms_state_table_+12 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 47, 0, ms_state_table_+14 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 48, 0, ms_state_table_+16 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 58, 0, ms_state_table_+23 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 59, 0, ms_state_table_+25 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 60, 0, ms_state_table_+26 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 61, 0, ms_state_table_+28 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 62, 0, ms_state_table_+30 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 64, 0, ms_state_table_+32 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 91, 0, ms_state_table_+9 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 95, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 97, 0, ms_state_table_+35 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 98, 0, ms_state_table_+38 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 99, 0, ms_state_table_+43 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 100, 0, ms_state_table_+53 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 101, 0, ms_state_table_+55 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 102, 0, ms_state_table_+59 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 105, 0, ms_state_table_+77 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 110, 0, ms_state_table_+79 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 111, 0, ms_state_table_+82 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 112, 0, ms_state_table_+84 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 113, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 114, 0, ms_state_table_+87 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 115, 0, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 116, 0, ms_state_table_+93 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 117, 0, ms_state_table_+97 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 118, 0, ms_state_table_+102 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 119, 0, ms_state_table_+105 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 123, 0, ms_state_table_+25 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 125, 0, ms_state_table_+25 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 40, 42, ms_state_table_+9 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 49, 57, ms_state_table_+22 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 65, 90, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 93, 94, ms_state_table_+9 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 103, 104, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 106, 109, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 120, 122, ms_state_table_+34 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::CONDITIONAL, 2, 0, ms_state_table_+112 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::CONDITIONAL, 2, 2, ms_state_table_+117 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 34, 0, ms_state_table_+114 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 92, 0, ms_state_table_+115 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 1, 33, ms_state_table_+113 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 35, 91, ms_state_table_+113 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 93, 255, ms_state_table_+113 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 1, 9, ms_state_table_+116 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 11, 255, ms_state_table_+116 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 34, 0, ms_state_table_+114 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM, 92, 0, ms_state_table_+115 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 1, 33, ms_state_table_+113 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 35, 91, ms_state_table_+113 },
    { ReflexCpp_::AutomatonApparatus::DfaTransition_::INPUT_ATOM_RANGE, 93, 255, ms_state_table_+113 }
};
BarfCpp_::Size const SteelScanner::ms_transition_count_ = sizeof(SteelScanner::ms_transition_table_) / sizeof(*SteelScanner::ms_transition_table_);

BarfCpp_::Uint32 const SteelScanner::ms_accept_handler_count_ = 47;

// ///////////////////////////////////////////////////////////////////////
// end of internal reflex-generated parser guts
// ///////////////////////////////////////////////////////////////////////


#line 57 "steel.reflex"

void SteelScanner::setBuffer(const char * pBuffer, const std::string &name)
{
	assert ( NULL != pBuffer );
	m_char_cursor = 0;
	m_line = 1;
	m_pBuffer = pBuffer;
	m_script_name = name;
}
int SteelScanner::ToInt(const std::string &text)
{
	std::istringstream str(text);
	int i;
	str >> i;

	return i;
}

double SteelScanner::ToFloat(const std::string &text)
{
	std::istringstream str(text);
	double d;
	str >> d;

	return d;
}

int SteelScanner::ToIntFromHex(const std::string &text)
{
	std::istringstream str(text);
	int i;

	str >> std::hex >> i;
	return i;
}


#line 1496 "SteelScanner.cpp"
